### ISSUE TITLE
Failed to load confluence-integration obsidian plugin

### ISSUE THREAD

**Issue by agustine-leo** [markdown-confluence/markdown-confluence#627]
Hi, I have an issue with the plugin. Previously it was working fine, but today I just realized it doesn't work anymore.
Plugin Version: 5.5.2
Obsidian Version: v1.5.8

Logs captured from dev tools.

> Plugin failure: confluence-integration TypeError: W_e.isDesktopCapturerEnabled is not a function
>     at eval (VM328 plugin:confluence-integration:44:184470)
>     at eval (VM328 plugin:confluence-integration:6:265)
>     at eval (VM328 plugin:confluence-integration:44:184861)
>     at eval (VM328 plugin:confluence-integration:6:265)
>     at eval (VM328 plugin:confluence-integration:44:190951)
>     at eval (VM328 plugin:confluence-integration:6:265)
>     at eval (VM328 plugin:confluence-integration:44:190998)
>     at eval (VM328 plugin:confluence-integration:6:265)
>     at anonymous (VM328 plugin:confluence-integration:1718:226)
>     at e.<anonymous> (app.js:1:2046123)
> (anonymous) @ app.js:1
> 4app.js:1 Plugin failure: confluence-integration TypeError: W_e.isDesktopCapturerEnabled is not a function
>     at eval (VM307 plugin:confluence-integration:44:184470)
>     at eval (VM307 plugin:confluence-integration:6:265)
>     at eval (VM307 plugin:confluence-integration:44:184861)
>     at eval (VM307 plugin:confluence-integration:6:265)
>     at eval (VM307 plugin:confluence-integration:44:190951)
>     at eval (VM307 plugin:confluence-integration:6:265)
>     at eval (VM307 plugin:confluence-integration:44:190998)
>     at eval (VM307 plugin:confluence-integration:6:265)
>     at anonymous (VM307 plugin:confluence-integration:1718:226)
>     at e.<anonymous> (app.js:1:2046123)
> 
> 

![image](https://github.com/markdown-confluence/markdown-confluence/assets/137710619/dfdb61c2-0b9c-48c4-95c7-9c3901c794cd)

**Comment by lenow55** [comment]
Hello, have the same problem. I try to install and use this plugin, but can't start.

**Comment by agustineleo** [comment]
I installed Obsidian using flatpak, downgraded to previous release fixed the issue for now.

```
flatpak update --commit=26c9563c28b3250935a00151e4efcb6b4a8488a6b1066b111cf943d882effca7 md.obsidian.Obsidian
flatpak mask md.obsidian.Obsidian # Freeze auto update
```

**Comment by agustine-leo** [comment]
I installed Obsidian using flatpak, downgraded to previous release fixed the issue for now.

```
flatpak update --commit=26c9563c28b3250935a00151e4efcb6b4a8488a6b1066b111cf943d882effca7 md.obsidian.Obsidian
flatpak mask md.obsidian.Obsidian # Freeze auto update
```

**Comment by lenow55** [comment]
Thank you, i downgraded version from 1.5.8-2 to 1.5.8-1 at archlinux and plugin works now.

**Comment by kylebcooke** [comment]
I'm in the same boat. I found this plugin today and was hoping to use it to streamline documentation processes. I will not be downgrading Obsidian, hoping this plugin is fixed soon!

**Comment by tiredcisadmin** [comment]
I am having the same issue on MacOS. Obsidian installed through Homebrew, but no other issues, so I do not believe this is imortant to the issue. 

This is the error I keep getting. Looks like it is missing a CSS file, which I assume is where the missing function below that is located. 

```js
app.js:1 Confluence Integration: styles.css not found
app.js:1 Plugin failure: confluence-integration TypeError: W_e.isDesktopCapturerEnabled is not a function
    at eval (plugin:confluence-integration:44:184470)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:184861)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190951)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190998)
    at eval (plugin:confluence-integration:6:265)
    at anonymous (plugin:confluence-integration:1718:226)
    at e.<anonymous> (app.js:1:2046123)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
```

**Comment by di-org** [comment]
I am also having this issue on Android, version 1.5.8(126).  Also the previous version I had installed couldn't enable the plugin, 1.4.something (unfortunately it updated before I could grab the whole version number).

**Comment by justin-parker** [comment]
Fixed my locally for now by editing the plugin's `main.js` file.
Remove the `W_e.isDesktopCapturerEnabled()` function call, and it will work with the latest version of Obsidian.  This is quick and dirty (sorry, but didn't have time to find this in source and create a proper PR, but wanted to at least share a quick fix for folks here that are in a pinch and don't want to downgrade Obsidian).

**Comment by t3knoid** [comment]
I am having the same issue under Windows with v1.5.11. The plugin installs. However, I could not enable it. I used the suggestion that @justin-parker suggested and now I can enable the plugin.

**Comment by gergan** [comment]
The problem is the dependency "@electron/remote": "^2.0.9", in packages/mermaid-electron-renderer/package.json
I have changed it to  "@electron/remote": "^2.1.2", and built the package again and it works, could create a pull request. But I don't see any activity in the repo, so I'm not sure if one will merge it

**Comment by AntoineLu** [comment]
> The problem is the dependency "@electron/remote": "^2.0.9", in packages/mermaid-electron-renderer/package.json
> I have changed it to "@electron/remote": "^2.1.2", and built the package again and it works, could create a pull request. But I don't see any activity in the repo, so I'm not sure if one will merge it

Hi @gergan can you tell more?
I'm running in the same trouble, I don't find the file you're talking about.

EDIT: @justin-parker's solution worked fine. Thanks! I wonder how did you find about it though.

**Comment by gergan** [comment]
> > The problem is the dependency "@electron/remote": "^2.0.9", in packages/mermaid-electron-renderer/package.json
> > I have changed it to "@electron/remote": "^2.1.2", and built the package again and it works, could create a pull request. But I don't see any activity in the repo, so I'm not sure if one will merge it
> 
> Hi @gergan can you tell more? I'm running in the same trouble, I don't find the file you're talking about.
> 
> EDIT: @justin-parker's solution worked fine. Thanks! I wonder how did you find about it though.

Sorry I had too much on my head - but here ist the patch, which fixes it for me 
[markdown-confluence-9ba7b11-fix.patch](https://github.com/markdown-confluence/markdown-confluence/files/15146652/markdown-confluence-9ba7b11-fix.patch)

**Comment by StefanD986** [comment]
I used @justin-parker workaround of removing the `||W_e.isDesktopCapturerEnabled()` in `main.js` of the plugin.

@gergan where do you apply the patch? on the Obsidian source?

Thanks for finding a workaround!

Update: Lately I also needed to remove `||W_e.isViewApiEnabled()`

**Comment by agustine-leo** [comment]
@StefanD986 you can find the `main.js` in `<your obsidian notes directory>/.obsidian/plugins/confluence-integration/`

**Comment by di-org** [comment]
@justin-parker - Nice, dude!  

I am growing increasing concerned that this simple, effective plugin has been abandoned; and it's only one of two publishing plugins.... and really, only one of one, as the other does not compare, IMO.

**Comment by jvsteiner** [comment]
@andymac4182 is the fellow behind this awesome plugin.  I know a couple people pinged him on DIscord.  He might just be on vacation at the moment.  I'd give him the benefit of the doubt - I know he put a lot of work into creating it last year.

**Comment by wgregorian** [comment]
> @andymac4182 is the fellow behind this awesome plugin. I know a couple people pinged him on DIscord. He might just be on vacation at the moment. I'd give him the benefit of the doubt - I know he put a lot of work into creating it last year.

Nine months (since the last commit) of vacation?! Baller. At any rate, the plug-in is in maintenance mode right now, but I share the sentiment with the others: we find it super helpful. If everyone was willing to incentivize the code maintainer through sponsorship, that might sweeten the pot; it isn't all altruistic. IMO, their time is a precious commodity we should cherish.

**Comment by jvsteiner** [comment]
I forked the repository, updated dependencies, and built the plugin to a working state for my own use.  I have published a patched release here, for those who might be looking for a short term solution: https://github.com/jvsteiner/markdown-confluence/releases/tag/v5.5.2_1

**Comment by AntoineLu** [comment]
> > > The problem is the dependency "@electron/remote": "^2.0.9", in packages/mermaid-electron-renderer/package.json
> > > I have changed it to "@electron/remote": "^2.1.2", and built the package again and it works, could create a pull request. But I don't see any activity in the repo, so I'm not sure if one will merge it
> > 
> > 
> > Hi @gergan can you tell more? I'm running in the same trouble, I don't find the file you're talking about.
> > EDIT: @justin-parker's solution worked fine. Thanks! I wonder how did you find about it though.
> 
> Sorry I had too much on my head - but here ist the patch, which fixes it for me [markdown-confluence-9ba7b11-fix.patch](https://github.com/markdown-confluence/markdown-confluence/files/15146652/markdown-confluence-9ba7b11-fix.patch)

Hi, How to use your patch exactly?

**Comment by jvsteiner** [comment]
on the releases page, you download `main.js` and replace the main.js file in the `.obsidian/plugins/confluence-integration` folder

**Comment by ghislainbourgin** [comment]
@jvsteiner What’s the best practice in this case? I reached out to the plugin but he doesn’t really have time to work on this.
So a partially non-working plugin remains in the community plugins, while your fix is working.
Can’t your version replace the original one (with due mention of course).

**Comment by ebarrere** [comment]
Is anyone willing to take over the maintenance of this plugin? I would sponsor them immediately if you can fix it and put it back in the community plugins list for install...

**Comment by jvsteiner** [comment]
I second the motion.  Can't do it myself - lack bandwidth

**Comment by jvsteiner** [comment]
the version I published before can also be used as a starting point - its open, and anyone can fork it.  I think to put it in the community list, all you need to do is mention the original source, and give it a new name.  "Markdown Confluence Returns"  or "Markdown Confluence Part Deux" spring to mind as options...

**Comment by andymac4182** [comment]
Fixed on `main` by #699 and will go out in the next release. Closing as completed.
