### ISSUE TITLE
Enable Confluence integration Error

### ISSUE THREAD

**Issue by texousliu** [markdown-confluence/markdown-confluence#645]
app.js:1 Plugin failure: confluence-integration TypeError: $xe.isDesktopCapturerEnabled is not a function
    at eval (plugin:confluence-integration:43:186681)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:43:187072)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:43:193162)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:43:193209)
    at eval (plugin:confluence-integration:6:265)
    at anonymous (plugin:confluence-integration:1689:226)
    at e.<anonymous> (app.js:1:2289222)
    at app.js:1:237079
    at Object.next (app.js:1:237184)
    at a (app.js:1:235902)

**Comment by tstackhouse** [comment]
Duplicate of #627?

**Comment by andymac4182** [comment]
This is the same Obsidian plugin load failure fixed on `main` by #699. It will go out in the next release. Closing as completed.
