### ISSUE TITLE
Failed to Load Plugin "Confluence-Integration"

### ISSUE THREAD

**Issue by Jonnokc** [markdown-confluence/markdown-confluence#646]
Hello,

After installing the plugin, I attempt to enable. Enabling fails with the error "Failed to Load Plugin "Confluence-Integration".

Running plugin version: 5.5.2
Obsidian version: Version 1.6.5 (Installer 1.6.5)

Macbook Apple Silicone.

All I'm seeing. Can plug other details if someone tells me where to look.

**Comment by metheu** [comment]
I'm having the exact same issue with the exact issue with the latest version on Obsidian (Version 1.6.5 (Installer 1.6.5)).

**Comment by jvsteiner** [comment]
me too - I think the upgrade broke something.

**Comment by solarisjon** [comment]
Seeing this as well opening dev tools I see 

> index.html:1 [Deprecation] The keyword 'inner-spin-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
app.js:1 Plugin failure: confluence-integration TypeError: W_e.isDesktopCapturerEnabled is not a function
    at eval (plugin:confluence-integration:44:184470)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:184861)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190951)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190998)
    at eval (plugin:confluence-integration:6:265)
    at anonymous (plugin:confluence-integration:1718:226)
    at e.<anonymous> (app.js:1:2292461)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1

**Comment by wgregorian** [comment]
Same issue as before, try this: https://github.com/markdown-confluence/markdown-confluence/issues/627#issuecomment-2121494900 - it seems to work.

**Comment by andymac4182** [comment]
This is the same Obsidian plugin load failure fixed on `main` by #699. It will go out in the next release. Closing as completed.
