### ISSUE TITLE
isDesktopCapturerEnabled is not a function

### ISSUE THREAD

**Issue by it-is-i** [markdown-confluence/markdown-confluence#651]
Hi,

I can install the plugin without issues. However, when I try to activate it, I get the following error:
Plugin failure: confluence-integration TypeError: W_e.isDesktopCapturerEnabled is not a function
    at eval (plugin:confluence-integration:44:184470)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:184861)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190951)
    at eval (plugin:confluence-integration:6:265)
    at eval (plugin:confluence-integration:44:190998)
    at eval (plugin:confluence-integration:6:265)
    at anonymous (plugin:confluence-integration:1718:226)
    at e.<anonymous> (app.js:1:2292629)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

Any ideas what the root-cause can be?

Thanks!

**Comment by VolkovIlia** [comment]
Any updates?

**Comment by it-is-i** [comment]
Unfortunately i haven't been able to work around it, nor did an update come along to fix this.

**Comment by jcfergus** [comment]
I just submitted a PR that fixes this here:  https://github.com/markdown-confluence/obsidian-integration/pull/3

**Comment by tstackhouse** [comment]
This is the same issue as reported in #672

**Comment by andymac4182** [comment]
Fixed on `main` by #699 and will go out in the next release. Closing as completed.
